/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myapp;

import config.db_configuration;
import internalPages.addReport;
import internalPages.puroksTbl;
import internalPages.resident;
import static internalPages.resident.res_tbl;
import java.awt.BasicStroke;
import java.awt.Color;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.Border;
import net.proteanit.sql.DbUtils;
import javax.swing.JTextField;


/**
 *
 * @author Mark
 */
public class viewPage extends javax.swing.JFrame {

    /**
     * Creates new form viewPage
     */
    public viewPage() {
        initComponents();
       jPanel3.setBackground(new Color(0,0,0,0));
      
    }
    
     Color navcolor = new Color(53,181,215);
     Color headcolor = new Color(102,102,255);
     Color bodycolor = new Color(153,153,255);

     Color hover = new Color(0,153,255);
     Color defButton = new Color(69,193,255);
    
    Border empty = BorderFactory.createEmptyBorder();
    
    void buttonBorderAnimation(JPanel panel){
    panel.setBackground(hover);
    panel.setBorder(BorderFactory.createLineBorder(Color.BLACK));
    panel.setBorder(BorderFactory.createStrokeBorder(new BasicStroke(2.0f)));
    
    }
     public void displayData(){
       
        try{
       
            db_configuration dbc = new db_configuration();
            ResultSet rs = dbc.getData("SELECT * FROM residents");
            res_tbl.setModel(DbUtils.resultSetToTableModel(rs));
       
        }catch(SQLException ex){
            System.out.println("Error Message: "+ex);
        }
    }

    void buttonDefaultColor(JPanel panel){
    panel.setBackground(defButton);
    panel.setBorder(empty);
    }
     public void fillRESIDENT() throws SQLException{
        
    db_configuration dbc = new db_configuration();
    ResultSet rs = dbc.getData("SELECT*FROM residents");
    resident rd = new resident();
    displayPane.add(rd).setVisible(true);
    resident.res_tbl.setModel(DbUtils.resultSetToTableModel(rs));
    }
      public void fillPurok() throws SQLException{
        
    db_configuration dbc = new db_configuration();
    ResultSet rs = dbc.getData("SELECT*FROM puroks");
    puroksTbl pt = new puroksTbl();
    displayPane.add(pt).setVisible(true);
    puroksTbl.ptbl.setModel(DbUtils.resultSetToTableModel(rs));
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */ 
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        navBar = new javax.swing.JPanel();
        dolphinPane = new javax.swing.JPanel();
        dashb = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        addReport = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        puroks = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        displayPane = new javax.swing.JDesktopPane();
        jLabel13 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        header = new javax.swing.JPanel();
        exitPane = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        mmzPane = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        navBar.setBackground(new java.awt.Color(69, 193, 215));
        navBar.setLayout(null);

        dolphinPane.setBackground(new java.awt.Color(53, 181, 215));
        dolphinPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dolphinPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dolphinPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dolphinPaneMouseExited(evt);
            }
        });
        dolphinPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashb.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        dashb.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashb.setText("RESIDENTS");
        dolphinPane.add(dashb, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        navBar.add(dolphinPane);
        dolphinPane.setBounds(0, 160, 240, 40);

        jPanel3.setBackground(new java.awt.Color(69, 193, 215));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(242, 242, 242));
        jLabel14.setText(" ←");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 30));

        navBar.add(jPanel3);
        jPanel3.setBounds(0, 0, 50, 40);

        addReport.setBackground(new java.awt.Color(53, 181, 215));
        addReport.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addReportMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addReportMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addReportMouseExited(evt);
            }
        });
        addReport.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("ADD COMPLAIN");
        addReport.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 170, 40));

        navBar.add(addReport);
        addReport.setBounds(0, 260, 240, 40);

        jTextField1.setBackground(new java.awt.Color(69, 193, 215));
        jTextField1.setForeground(new java.awt.Color(69, 193, 215));
        jTextField1.setBorder(null);
        navBar.add(jTextField1);
        jTextField1.setBounds(20, 560, 0, 20);

        jComboBox1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dolphin", "Bolinao", "Mamsa" }));
        navBar.add(jComboBox1);
        jComboBox1.setBounds(10, 360, 220, 30);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 2, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  PUROKS");
        navBar.add(jLabel1);
        jLabel1.setBounds(10, 340, 220, 20);

        puroks.setBackground(new java.awt.Color(53, 181, 215));
        puroks.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                puroksMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                puroksMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                puroksMouseExited(evt);
            }
        });
        puroks.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("PUROKS");
        puroks.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 40));

        navBar.add(puroks);
        puroks.setBounds(0, 210, 240, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\Mark\\Pictures\\texture-with-blue-paint_1048-5111.jpg")); // NOI18N
        jLabel7.setText("jLabel6");
        navBar.add(jLabel7);
        jLabel7.setBounds(-6, 0, 250, 590);

        jPanel1.add(navBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 590));

        displayPane.setBackground(new java.awt.Color(0, 153, 255));

        jLabel13.setBackground(new java.awt.Color(153, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/effective-employee-management.jpg"))); // NOI18N
        displayPane.add(jLabel13);
        jLabel13.setBounds(-200, 0, 820, 560);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        displayPane.add(jPanel5);
        jPanel5.setBounds(420, -40, 100, 100);

        jPanel1.add(displayPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, 620, 520));

        header.setBackground(new java.awt.Color(0, 153, 153));
        header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exitPane.setBackground(new java.awt.Color(0, 153, 153));
        exitPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitPaneMouseExited(evt);
            }
        });
        exitPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Corbel Light", 1, 20)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(212, 206, 206));
        jLabel8.setText(" x");
        exitPane.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 20, 30));

        header.add(exitPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 0, 40, 30));

        mmzPane.setBackground(new java.awt.Color(0, 153, 153));
        mmzPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmzPaneMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mmzPaneMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mmzPaneMouseExited(evt);
            }
        });
        mmzPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(212, 206, 206));
        jLabel9.setText("—");
        mmzPane.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, -10, 20, 50));

        header.add(mmzPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 0, 40, 30));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 3, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("BARANGAY RESIDENT INFORMATION  & REPORT SYSTEM");
        header.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 400, 30));

        jPanel1.add(header, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 620, -1));

        jPanel6.setBackground(new java.awt.Color(0, 204, 204));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel5.setText("RESIDENT'S PAGE ");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 230, 40));

        jPanel4.setBackground(new java.awt.Color(0, 204, 204));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel6.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 0, 50, 40));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconsFolder/icons8-house-48.png"))); // NOI18N
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, 40));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 620, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 859, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void dolphinPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dolphinPaneMouseClicked
        dashb.setForeground(Color.WHITE);
        jLabel3.setForeground(Color.BLACK);
        jLabel4.setForeground(Color.BLACK);
        jLabel5.setText("RESIDENT PAGE");
        resident r = new resident();
       
        displayPane.add(r).setVisible(true);
           try{
            fillRESIDENT();
        }catch(SQLException e)
        {
            System.out.println("Error is: "+e);
        }
    }//GEN-LAST:event_dolphinPaneMouseClicked

    private void dolphinPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dolphinPaneMouseEntered
        dolphinPane.setBackground(bodycolor);
    }//GEN-LAST:event_dolphinPaneMouseEntered

    private void dolphinPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dolphinPaneMouseExited
        dolphinPane.setBackground(navcolor);
    }//GEN-LAST:event_dolphinPaneMouseExited

    private void exitPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseClicked
          int a = JOptionPane.showConfirmDialog(null, "Confirm Exit?");
        if(a == JOptionPane.YES_OPTION){
        System.exit(0);
        }
    }//GEN-LAST:event_exitPaneMouseClicked

    private void exitPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseEntered
        exitPane.setBackground(new Color(204,0,51));
    }//GEN-LAST:event_exitPaneMouseEntered

    private void exitPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitPaneMouseExited
        exitPane.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_exitPaneMouseExited

    private void mmzPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmzPaneMouseClicked
        setState(ICONIFIED);
    }//GEN-LAST:event_mmzPaneMouseClicked

    private void mmzPaneMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmzPaneMouseEntered
        mmzPane.setBackground(new Color(153,153,153));
    }//GEN-LAST:event_mmzPaneMouseEntered

    private void mmzPaneMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mmzPaneMouseExited
        mmzPane.setBackground(new Color(0,153,153));
    }//GEN-LAST:event_mmzPaneMouseExited

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
       this.dispose();
        dashBoard dbp = new dashBoard();
        dbp.setVisible(true);    
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
    
       resident res = new resident();
        displayPane.add(res).setVisible(true);
  
           try{
            fillRESIDENT();
        }catch(SQLException e)
        {
            System.out.println("Error is: "+e);
        }
    }//GEN-LAST:event_jPanel4MouseClicked

    private void addReportMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportMouseExited
        addReport.setBackground(navcolor);
    }//GEN-LAST:event_addReportMouseExited

    private void addReportMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportMouseEntered
        addReport.setBackground(bodycolor);
     
    }//GEN-LAST:event_addReportMouseEntered

    private void addReportMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addReportMouseClicked
        jLabel3.setForeground(Color.WHITE);
        jLabel4.setForeground(Color.BLACK);
        dashb.setForeground(Color.BLACK);
        jLabel5.setText("REPORT PAGE");
        addReport ar = new addReport();
        displayPane.add(ar).setVisible(true);
          
    }//GEN-LAST:event_addReportMouseClicked

    private void puroksMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puroksMouseClicked
        jLabel4.setForeground(Color.WHITE);
        jLabel3.setForeground(Color.BLACK);
        dashb.setForeground(Color.BLACK);
        
        try{                                    
              jLabel5.setText("PUROK PAGE");
              puroksTbl pt = new puroksTbl();
              displayPane.add(pt).setVisible(true);
        
              try{
                  fillPurok();
              }catch(SQLException e)
              {
                  System.out.println("Error is: "+e);
              }
              
          }catch(SQLException ex)
        {
            Logger.getLogger(viewPage.class.getName()).log(Level.SEVERE, null, ex);
        }
         
    }//GEN-LAST:event_puroksMouseClicked

    private void puroksMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puroksMouseEntered
           puroks.setBackground(bodycolor);
    }//GEN-LAST:event_puroksMouseEntered

    private void puroksMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_puroksMouseExited
          puroks.setBackground(navcolor);
    }//GEN-LAST:event_puroksMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new viewPage().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel addReport;
    public static javax.swing.JLabel dashb;
    public static javax.swing.JDesktopPane displayPane;
    private javax.swing.JPanel dolphinPane;
    private javax.swing.JPanel exitPane;
    private javax.swing.JPanel header;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    public static javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel jLabel4;
    public static javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JPanel mmzPane;
    private javax.swing.JPanel navBar;
    private javax.swing.JPanel puroks;
    // End of variables declaration//GEN-END:variables

    private void buttonBorderAnimation(JTextField search) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
